### ISSUE TITLE
Update for 2.0.1 - Teal Mask DLC

### ISSUE THREAD

**Issue by pineapple21** [foohyfooh/PKHeXPluginPile#19]
Add Kitakami Pokedex to the list of sort options.

 - Unsure if this is supposed to be in the pull requests but I don't know how to create that.

**Comment by foohyfooh** [comment]
This set of plugins is built using the [PKHeX nuget Package](https://www.nuget.org/packages/PKHeX.Core) which hasn't been updated despite PKHeX being updated. So at the moment I cannot update the plugins.

**Comment by pineapple21** [comment]
Understood. Thanks for the info!

**Comment by foohyfooh** [comment]
I was able to add support using a hacky method and this mismatch of PKHeX binary version and plugin PKHeX version doesn't appear to be causing any issues so this should solve your issue,

**Comment by pineapple21** [comment]
Was happy waiting but this is even better! Thanks a bunch :)
