### ISSUE TITLE
Special Pokémon Finder	plugin is not showing in tools menu on latest PKHex

### ISSUE THREAD

**Issue by GiftedK** [foohyfooh/PKHeXPluginPile#32]
Special Pokémon Finder	plugin is not showing in tools menu on latest PKHex, please check.

**Comment by foohyfooh** [comment]
What specific versions of PKHeX and the plugin are you using?

**Comment by GiftedK** [comment]
I’ve tried both latest stable release of PKHex version 24.7.27 and the development build version 24.7.27+27. While using PKHex Plugin Pile version 1.8.2, I’ve also used the individual Special Pokemon Finder plugin, however, both won’t show in tools menu of PKHex.

**Comment by foohyfooh** [comment]
I am still not sure why the individual plugin isn't loading but I have been able to get it showing up with including both the PluginPile.dll (which doesn't include PluginPile.SpecialPkmnFinder built in right now) and PluginPile.SpecialPkmnFinder.dll in the plugin folder

**Comment by GiftedK** [comment]
I can help in testing if you need me to.

> I am still not sure why the individual plugin isn't loading but I have been able to get it showing up with including both the PluginPile.dll (which doesn't include PluginPile.SpecialPkmnFinder built in right now) and PluginPile.SpecialPkmnFinder.dll in the plugin folder

**Comment by foohyfooh** [comment]
I had forgotten to include the libraries which bundles the common dependencies into the plugin which made it not able to load and thus not show up in PKHeX.
Closed by commit a046a37c59e6e8d7ef84981b90d1b125e81caf50
